// Renders src/data/legal.ts to public/<doc>/index.html — the public Privacy
// Policy, Terms, account-deletion and support pages that ship with the web
// build. Run `npm run gen:legal` after editing legal.ts; CI fails on drift.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadTs } from './load-ts.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const { LEGAL, LEGAL_DOCS, sectionBlocks } = await loadTs(path.join(root, 'src/data/legal.ts'));

const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
// Escape, then link email addresses.
const inline = (s) =>
  esc(s).replace(/[\w.+-]+@[\w-]+\.[\w.]+[\w]/g, (m) => `<a href="mailto:${m}">${m}</a>`);

const nav = LEGAL_DOCS.map((d) => `<a href="../${d.id}/">${esc(d.shortTitle)}</a>`).join('\n      ');

function render(doc) {
  const body = doc.sections
    .map((s) => {
      const blocks = sectionBlocks(s).map((b) =>
        b.kind === 'p'
          ? `<p>${inline(b.text)}</p>`
          : `<ul>\n${b.items.map((i) => `  <li>${inline(i)}</li>`).join('\n')}\n</ul>`
      );
      return `<section>\n<h2>${esc(s.heading)}</h2>\n${blocks.join('\n')}\n</section>`;
    })
    .join('\n');

  return `<!doctype html>
<!-- Generated by scripts/gen-legal.mjs from src/data/legal.ts. Do not edit by hand. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(doc.title)} · ${esc(LEGAL.appName)}</title>
<meta name="description" content="${esc(doc.intro)}">
<style>
  :root { --bg: #08080A; --surface: #121214; --text: #F5F5F7; --muted: #A1A1AA; --accent: #FF2E7E; --line: rgba(255,255,255,0.1); color-scheme: dark; }
  @media (prefers-color-scheme: light) { :root { --bg: #FAFAFA; --surface: #FFFFFF; --text: #18181B; --muted: #52525B; --accent: #C2185B; --line: rgba(0,0,0,0.1); color-scheme: light; } }
  * { box-sizing: border-box; }
  body { margin: 0; background: var(--bg); color: var(--text); font: 16px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; }
  main { max-width: 720px; margin: 0 auto; padding: 32px 16px 64px; }
  nav { display: flex; flex-wrap: wrap; gap: 8px 18px; font-size: 14px; padding-bottom: 16px; border-bottom: 1px solid var(--line); }
  nav a { color: var(--muted); text-decoration: none; }
  nav a[aria-current] { color: var(--accent); }
  .brand { font-weight: 700; letter-spacing: 0.04em; color: var(--accent); text-decoration: none; display: inline-block; margin-bottom: 12px; }
  h1 { font-size: 32px; line-height: 1.2; margin: 28px 0 8px; }
  .updated { color: var(--muted); font-size: 14px; margin: 0 0 16px; }
  .intro { font-size: 18px; }
  h2 { font-size: 19px; margin: 32px 0 8px; }
  ul { padding-left: 22px; }
  li { margin: 6px 0; }
  a { color: var(--accent); }
  footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid var(--line); color: var(--muted); font-size: 14px; }
</style>
</head>
<body>
<main>
  <a class="brand" href="../">WILDHOUR</a>
  <nav>
      ${nav.replace(`href="../${doc.id}/"`, `href="../${doc.id}/" aria-current="page"`)}
  </nav>
  <h1>${esc(doc.title)}</h1>
  <p class="updated">Last updated ${esc(LEGAL.updated)}</p>
  <p class="intro">${inline(doc.intro)}</p>
${body}
  <footer>${esc(LEGAL.appName)} is a self-awareness tool, not a medical service. Contact: ${inline(LEGAL.contactEmail)}</footer>
</main>
</body>
</html>
`;
}

for (const doc of LEGAL_DOCS) {
  const dir = path.join(root, 'public', doc.id);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'index.html'), render(doc));
  console.log(`wrote public/${doc.id}/index.html`);
}
